from .TextAnalysisResponseDTO import TextAnalysisResponseDTO
from .TextAnalaysisFeedbackReviewResponseDTO import TextAnalysisFeedbackReviewResponseDTO

__all__ = ["TextAnalysisResponseDTO", "TextAnalysisFeedbackReviewResponseDTO"]