CREATE TABLE IF NOT EXISTS mlops_tbl_knowledge (
    `id` VARCHAR(36) PRIMARY KEY,
    `prompt` TEXT,
    `label` SMALLINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT NULL,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);